### ISSUE TITLE
Footer of 'how-do-you-measure..." links to main page, not the other brochure page

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduWebsite2015#23]
http://staging.wikiedu.org/how-do-you-measure-the-difference-that-open-knowledge-makes/

**Comment by thenickcox** [comment]
This is a good opportunity to circle back on this. I wrote about this in Basecamp, but that probably wasn't the right place. :)

The page doesn't link to the other brochure page because I wasn't sure what we wanted the URL slugs to be. /how-do-you-measure-the-difference-that-open-knowledge-makes and /does-editing-wikipedia-change-a-students-life are _really_ long. Did we want to cut those down? If not, I'll just throw those in the `href` of the respective links and call it a day!

**Comment by ragesoss** [comment]
If subpages without parents are okay, we want these slugs:
/changing/classrooms (for how-do-you-measure) and /changing/students (for
does-editing-wikipedia-change)

**Comment by thenickcox** [comment]
Okay! These are changes to the slugs are on staging now. And the footers of the pages link to each other.
