### ISSUE TITLE
Contact form does not have a field for 'name'

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduWebsite2015#6]
The form at the bottom of 'for-instructors' now lacks the essential Name field.

**Comment by dmak78** [comment]
@ragesoss All fixed up, and due to some of the changes the way to hide or show the contact form on a page is to add a custom field attribute: show_contact_form set to 'true'. See existing pages for example.

**Comment by ragesoss** [comment]
@dmak78 I can't find this show_contact_form attribute. How do I set it?

**Comment by dmak78** [comment]
@ragesoss 
a little more info: the form by design won't show up on any 'blog/post/archive/search' pages, but for non blog pages, e.g. for media, you would go to Edit a given Page.

![screen shot 2015-05-27 at 3 22 45 pm](https://cloud.githubusercontent.com/assets/543860/7848880/9f600fea-0484-11e5-87cb-9659c1a7244f.png)

Scroll down to the Custom Fields and add 'show_contact_form' from the dropdown and put true in the field. False won't do anything; the default is for it not to show up. 

![screen shot 2015-05-27 at 3 23 06 pm](https://cloud.githubusercontent.com/assets/543860/7848886/abd812d6-0484-11e5-8ebc-facf1ef3e4c4.png)

It may be that you are not seeing Custom Fields at all; it may have to explicitly say you want to see it. In that case go to the very top right of the Edit Page where it says Screen Options. 

![screen shot 2015-05-27 at 3 23 01 pm](https://cloud.githubusercontent.com/assets/543860/7848890/b40827f2-0484-11e5-9923-5d64291610cb.png)

Open that and select Custom Fields, and you show be seeing them at the bottom of the page at that point.

Lemme know if its still a mystery.

**Comment by ragesoss** [comment]
Aha! Enabling them via Screen Options was what I needed to do. Thanks @dmak78
