### ISSUE TITLE
Hero images often get framed awkwardly

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduWebsite2015#7]
It would be nice to have a little more control over how the hero images play against the text, and how they reframe for different window sizes.

**Comment by thenickcox** [comment]
Here are a few solutions Riley and I came up with.
1. Give the image a `max-width` property, decrease height, add light background to `html`:
   
   ![screen shot 2015-07-28 at 2 44 14 pm](https://cloud.githubusercontent.com/assets/702327/8945229/76f20f22-353a-11e5-9e1f-3924c8ad8cad.png)
2. Decrease the height of the photo at largest size, drop headline down into body:
   
   ![screen shot 2015-07-28 at 3 03 23 pm](https://cloud.githubusercontent.com/assets/702327/8945235/8af6394e-353a-11e5-8d7d-f72b0a686850.png)
3. Embrace the hugeness of the images and their impact, increase the height and type size:
   
   ![screen shot 2015-07-28 at 3 06 26 pm](https://cloud.githubusercontent.com/assets/702327/8945238/9e8aff58-353a-11e5-88c3-865739c5f5ff.png)

A warning that any of these fixes will almost inevitably cause some images not to work well with the layout. (As it was, each required some tinkering with the photo that, when applied, didn't seamlessly translate into another image we tried.) As we discussed, you've got a lot of images with a lot of different focal points. It might be worth it to introduce some sort of editorial style guide for them.

What do you think of any of these approaches? If you can load the screenshots at full size, that'd help give perspective.

**Comment by thenickcox** [comment]
As a side note, what data do we have in the form of analytics to see how many and what percent of your users see what we do at screen widths above, say, 1600px? That would definitely help us make a more informed decision.

**Comment by ragesoss** [comment]
@thenickcox WordPress Jetpack stats doesn't seem to have screen resolution info, but I have more detailed stats from Piwik from the dashboard, and the demographics are likely similar. Here's the breakdown for visits by screen resolution for July:

1920x1080   73
1366x768    72
2560x1440   68
1280x720    56
1280x800    42
1680x1050   28
1440x900    24
2560x1600   21
1800x1125   10
360x640     6
640x1136    6
750x1334    6
1280x1024   6
1536x864    6
1536x2048   6
3360x2100   5
768x1024    4
1600x900    4
1920x1200   4
3200x1800   4
1024x768    3
1242x698    3
1301x731    3
1234x823    2
1242x2208   2
1360x768    2
1506x1205   2
1727.9999   2
2880x1800   2
184x246     1
230x265     1
240x301     1
320x202     1
320x570     1
1024x600    1
1200x1600   1
1280x768    1
1324x745    1
1707x960    1
unknown     1

**Comment by ragesoss** [comment]
@thenickcox We're interested in learning more about #1 and #3. Is the idea (in both cases) that the aspect ratio of the image remains constant (looks like almost 3:1) as the screen width changes?

And is the text size constant for each breakpoint, so that there would be some (but less) shift in the way the image and text interact, as screen width changes?

#3 is more visually appealing, if it can really be made to work consistently across screen sizes.

**Comment by thenickcox** [comment]
My first question around Piwik is the significance of those screen resolutions. Because some of them seem non-standard (e.g., 230x265, 1506x1205), is it reasonable to assume that those figures aren't just overall screen resolutions, but the actual window size of their browser as they're browsing?

With regard to proposals #1 and #3, we could change the aspect ratio at certain breakpoints to make the image and text make more sense together. I want to reiterate, though, that because so many of the images have different focal points, that some of them are going to take some massaging to make them conform to whatever solution we choose.

It sounds like the next step would be for me to put #3 on staging and let you play with it, including seeing which images break it and how?

**Comment by ragesoss** [comment]
Yeah, having number 3 on staging would be great!

I'll see what I can learn about the Piwik data.

**Comment by thenickcox** [comment]
Were you able to view #3 at full size and on a large monitor? The aspect ratio is roughly 2.85:1.

**Comment by ragesoss** [comment]
Yes. (2.83 is what I had calculated with a ruler. :-) )

If we could do center cropping, with extra image being added at both the top and bottom when the aspect ratio changes, but text still anchored at the bottom of the crop, I think that could potentially work well in terms of finding images that fit from large monitor all the way down to mobile.

**Comment by ragesoss** [comment]
I think the Piwiki data is whatever (full) screen size the browser provides to the Piwik javascript. For desktops, I think that's pretty consistently the actual screen resolution, but I'm guessing that mobile devices play lots of different tricks.

In any case, it's clear that a sizable portion of visits come from screens wider than 1600.

If you want detailed longer-term stats for the blog itself, we could also install Piwik there.

**Comment by thenickcox** [comment]
Okay! This is on staging. Possibly the best illustration of this is [here](http://staging.wikiedu.org/changing/students/). Note that there are about 5px between ~400px and ~2556px wide that fall between breakpoints and cause the header image to jump a bit. But this is more for illustration purposes. Treat it as a mockup/experiment.

**Comment by ragesoss** [comment]
Thanks! The basic idea of how this behaves from ~1300px down to mobile is just what we want, and the image cropping that happens after it reaches max height (which seems to be right around 1300) is at least a lot more controllable.

I do note that the aspect ratio in this experiment is ~2:1 instead of the 2.85:1 from the static mocks. We definitely need to pick a single aspect ratio and stick with it. I think 2:1 will be much easier to find good crops for with our current stock of imagery, which is mostly 3:2 in the originals.

Let's move forward with the number 3 concept; next step is to get a polished implementation of it on staging, and then we can start making the appropriate crops.

**Comment by thenickcox** [comment]
The problem with a single aspect ratio from 2556px down to 320px is that the cropping will be much less controllable, and that will basically confine you to images where the focal point is directly in the center.

Although now I think about it, I _guess_ we could just resize it dynamically as the browser changes dimensions with JS rather than through media queries, which would have to be extremely extensive to cover all the breakpoints.

If maintaining the aspect ratio is the most important thing, that's probably the best way I could think of to implement it. What do you think about that solution?

**Comment by ragesoss** [comment]
The current experiment pretty much does maintain the aspect ratio from 1300px down. Above that, the image will take over the screen if we maintain aspect ratio. I think it makes sense to cap the height in the experiment, and crop from the bottom. The best alternative, I think, is the path sketched out in number 1 (which, if I interpret correctly, would essential behave exactly like number 3, until it expands beyond the top breakpoint of ~1300px)... except that neither Eryk nor I think the gray is good.

So, at this point I think we want to move forward with the experiment version, just with whatever tweaking it takes to make it a little more consistent and less jumpy as you go down from 1300 to 320.

**Comment by thenickcox** [comment]
By "crop from the bottom" do you mean anchor the image to the bottom, or to the top? The images I've tried (/changing/students and /changing/classrooms) work best when the height is constrained and the image is positioned _toward_ the bottom:

![screen shot 2015-07-30 at 1 07 14 pm](https://cloud.githubusercontent.com/assets/702327/8993818/319095c4-36bc-11e5-8626-8ed06f3247bc.png)
![screen shot 2015-07-30 at 1 08 44 pm](https://cloud.githubusercontent.com/assets/702327/8993823/3762c47c-36bc-11e5-895a-8f50ec1891a9.png)

**Comment by ragesoss** [comment]
Okay, let's try your suggestion.

**Comment by thenickcox** [comment]
It's pretty quick. Let's stage it and you can play with it.

## Edit

Didn't mean to close.

**Comment by thenickcox** [comment]
Yeah, so this works great on the brochure pages, but not on pages like [instructors](http://staging.wikiedu.org/for-instructors/) and [partnerships](http://staging.wikiedu.org/partnerships/). In reality, these are all very different images. We're going to have to come up with a more versatile approach that will work for all of your photography, assuming you prefer making the layout fit your photography, rather than the other way around.

It is also completely wrong on the homepage, but you were talking about changing that image anyway, right?

**Comment by thenickcox** [comment]
One potential solution is putting a variable (custom fields) in the page that we access from the CSS that allows the admin to pick a third of the image to focus on at large sizes: top third, middle third, or bottom third, and just have CSS classes that hook into that? That'd be a bit more versatile, but I'm not sure how savvy your admin users might be at thinking of that and adding it to the custom field every time.

**Comment by ragesoss** [comment]
If it defaults to middle, that will work well.

**Comment by thenickcox** [comment]
Okay. On the [instructors](http://staging.wikiedu.org/for-instructors/) page, I've set a custom field `image_focal_point` with a value of `top`, and you can see that image appearing as you'd hope, whereas on the [partnerships](http://staging.wikiedu.org/partnerships/) page, I haven't set it, and it defaults to center.

This commit broke the blog, but you can get a sense of it with the other images.

BTW, values for `image_focal_point` are `top`, `middle` (default), or `bottom`. That really only covers how far up or down the image is. There's not an option for horizontal alignment.

## Edit

Actually, the commit didn't break the blog. I didn't have parity in my `/plugins` directory between prod, staging, and dev. We're all good now.

**Comment by thenickcox** [comment]
Good morning, @ragesoss.

As promised, I've fixed the issues with the framing on mobile and the blog and [staged them](http://staging.wikiedu.org/blog/2015/07/01/wikipedia-theories/).

(That link is to a post with a too-long title, which is the issue I mentioned on Friday. [Here](http://staging.wikiedu.org/blog/2015/06/22/director-of-programs/) is a post which works as expected.)

As a note, the menu item "For Media" was recently added on production, which causes the layout to break at certain breakpoints. Is that something we could put under "About Us" to maintain the design across breakpoints? Otherwise, we're going to have to rethink the menu.

**Comment by ragesoss** [comment]
This looks great! Eryk is on vacation starting tomorrow, so I think we are going to hold off on deploying this to production until around August 18 — so that Eryk can go through and do image resizing and tweaking as soon as possible afterwards.

We probably want to rethink the content of the menu soonish, as we figure out how to fit in the brochure pages and some other things we have planned. So once we have a clearer idea on the content constraints, we should take another pass at the menu.

**Comment by thenickcox** [comment]
Just wanted to confirm that we're all good from our end, and I'll be ready to take a look at the menu when you are! And definitely have Eryk chime in when he's back from vacation.

**Comment by ragesoss** [comment]
We're ready to go on deploying to production.
